### PR TITLE
Fix web view zooming is not working in pop up window

### PR DESCRIPTION
**Pull request by quanglam2807**

### CODE REVIEW

**Comment by martifenosa** [comment]
Hi, I think this issue is not fixed.
In gmail tabs I can zoom IN but not OUT. Can't find any way to do so, I've clicked the cmd+"-" by mistake and now can't go back. Not on the url bar or with the cmd+"+". 

I'll remove this gmail tab and add it again hope this works for now.

**Comment by hacknug** [comment]
> In gmail tabs I can zoom IN but not OUT.

@martifenosa You can restore the default zoom level you can using `CMD`+`0` or zoom in with `CMD`+`=`. Keyboard shortcuts for this are listed under the View menu :wink:

@quanglam2807 any reason to not use `CMD`+`+` like most people would expect? Maybe a Windows or Linux thing?

**Comment by quanglam2807** [comment]
@martifenosa I honestly don't know what went wrong, but zooming out still works well for you.

@hacknug Thank you for the input. Actually, on most computer keyboards, `=` and `+` are actually the same key. To input `+`, you'll need to press `Shift` and `=`.  So `Cmd` `+` would actually mean `Cmd` `Shift` `=` (I know I didn't explain it well). But anyway, despite what is shown, you can use `Cmd``+` to zoom in. I'll see if I can display it similarly to other apps (Detailed: https://github.com/electron/electron/issues/5256)

**Comment by hacknug** [comment]
> Actually, on most computer keyboards

I guess this means US keyboards or something like that. I'm 99.99% sure he has the exact same keyboard layout as I do (we're ex-coworkers haha) so this should solve his issue.

Not sure how other apps handle this kind of shortcut localization but if sounds like something that could get really complex in my head so `CMD`+`=` feels like a great way to zoom in haha.

Thanks for all the work you put into the app :heart:

**Comment by quanglam2807** [comment]
@hacknug Thank you for all the support! Would you mind sharing which keyboard you're using? Maybe I can find a way to workaround this.

**Comment by hacknug** [comment]
This is the layout our keyboards use (we both use laptops though): https://www.apple.com/es/shop/product/MLA22Y/A/magic-keyboard-espa%C3%B1ol

**Pull request merged**
